"""nao-sim: a NAO in a box. The front door re-exports what a caller needs (specs/runtime/api.md)."""

from nao_sim.audio_output import (
    AudioSink,
    DevicePlayer,
    MemorySink,
    NullSink,
    Playback,
    WavSink,
)
from nao_sim.config import (
    AudioInputSettings,
    AudioInputSource,
    AudioOutputMode,
    AudioOutputSettings,
    ConfigError,
    MonoPolicy,
    NaoqiSettings,
    NaoqiVersion,
    NaoSimConfig,
    SpeechEngine,
    SpeechSettings,
    VideoInputSettings,
    VideoInputSource,
    ViewerSettings,
    ViewerVariant,
)
from nao_sim.docker_images import check_images, fetch_and_build_images
from nao_sim.errors import (
    BootError,
    DeviceNotBuiltError,
    DockerUnavailableError,
    FetchError,
    ImageBuildError,
    ImagesMissingError,
    ImagesOutdatedError,
    MissingExtraError,
    NaoSimError,
    NotRunningError,
    PortInUseError,
)
from nao_sim.sim import NaoSim
from nao_sim.stack import (
    ContainerState,
    NaoSimStatus,
    StackStatus,
    cleanup,
    read_status,
)

__all__ = [
    "AudioInputSettings",
    "AudioInputSource",
    "AudioOutputMode",
    "AudioOutputSettings",
    "AudioSink",
    "BootError",
    "ConfigError",
    "ContainerState",
    "DeviceNotBuiltError",
    "DevicePlayer",
    "DockerUnavailableError",
    "FetchError",
    "ImageBuildError",
    "ImagesMissingError",
    "ImagesOutdatedError",
    "MemorySink",
    "MissingExtraError",
    "MonoPolicy",
    "NaoSim",
    "NaoSimConfig",
    "NaoSimError",
    "NaoSimStatus",
    "NaoqiSettings",
    "NaoqiVersion",
    "NotRunningError",
    "NullSink",
    "Playback",
    "PortInUseError",
    "SpeechEngine",
    "SpeechSettings",
    "StackStatus",
    "VideoInputSettings",
    "VideoInputSource",
    "ViewerSettings",
    "ViewerVariant",
    "WavSink",
    "check_images",
    "cleanup",
    "fetch_and_build_images",
    "read_status",
]
